version: '3'
services:
  app:
    container_name: php-app
    build: ./docker/app
    volumes:
      - ./src:/var/www
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_DATABASE=portfolio
      - DB_USERNAME=portfolio
      - DB_PASSWORD=portfolio

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "8902:80"
    depends_on:
      - app
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  database:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: portfolio
      MYSQL_USER: portfolio
      MYSQL_PASSWORD: portfolio
      TZ: "Asia/Tokyo"
    ports:
      - "4401:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
