version: '3'
services:
  app:
    container_name: php-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src:/var/www
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_DATABASE=portfolio
      - DB_USERNAME=portfolio
      - DB_PASSWORD=portfolio

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "3472:80"
    depends_on:
      - app
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  database:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: portfolio
      MYSQL_USER: portfolio
      MYSQL_PASSWORD: portfolio
      TZ: "Asia/Tokyo"
    ports:
      - "45401:3306"
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

  test_database:
    container_name: mysql-test
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: app_test
      MYSQL_DATABASE: app_test
      MYSQL_USER: app_test
      MYSQL_PASSWORD: app_test
      TZ: "Asia/Tokyo"
    ports:
      - "9923:3306"
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
